---
  - name: Install MongoDB
    package: 
      name: mongodb
      state: present
      update_cache: true

  - name: Ensure MongoDB service is running
    service:
      name: mongodb
      state: started

  - name: Copy FastAPI app code
    copy:
      src: "app"
      dest: "/root/"

  - name: Install Pip3
    package: 
      name: python3-pip
      state: present
      update_cache: true

  - name: Install FastAPI and dependencies
    pip:
      requirements: "/root/app/requirements.txt"
      executable: "/usr/bin/pip3"
    
  - name: Install supervisor
    package: 
      name: supervisor
      state: present
      update_cache: true

  - name: Copy uvicorn config for supervisor
    template:
      src: uvicorn.conf.j2
      dest: /etc/supervisor/conf.d/uvicorn.conf

  - name: Reread supervisor
    command: supervisorctl reread

  - name: Update supervisor
    command: supervisorctl update 