---
  - hosts: r1
    pre_tasks:
      - name: Make sure eth9 gets IP
        shell: dhclient eth9
    roles:
      - bird
    tags: bird

  - name: Include kubespray tasks
    include: kubespray/cluster.yml
    tags: kubespray

  - hosts: kube-master[0]
    roles:
      - metallb
    tags: metallb

  - hosts: kube-master[0]
    roles:
      - nginx-ingress
    tags: nginx-ingress

  - hosts: kube-master[0]
    roles:
      - helm-operator
    tags: helm-operator

  - hosts: kube-master[0]
    roles:
      - mongodb
    tags: mongodb

  - hosts: k8s-cluster
    roles:
      - helmmec
    tags: helmmec

  - hosts: meo
    roles:
      - meo
    tags: meo