---
  - name: "Kubernetes Apps | Lay Down Nginx Ingress service"
    template: { src: "{{ item }}.j2", dest: "{{ kube_config_dir }}/{{ item }}" }
    with_items: ["ingress-svc.yml"]
    register: "rendering"
    when:
      - "inventory_hostname == groups['kube-master'][0]"

  - name: "Kubernetes Apps | Install and configure Nginx Ingress service"
    kube:
      name: "Nginx Ingress Service"
      kubectl: "{{ bin_dir }}/kubectl"
      filename: "{{ kube_config_dir }}/{{ item.item }}"
      state: "{{ item.changed | ternary('latest','present') }}"
    with_items: "{{ rendering.results }}"
    when:
      - "inventory_hostname == groups['kube-master'][0]"