# coding: utf-8

"""
    MEO Mm1 AppPkgMgmt API

    Implementation of Mm1.AppPkgm APIs  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import meo_client
from meo_client.models.operational_state import OperationalState  # noqa: E501
from meo_client.rest import ApiException

class TestOperationalState(unittest.TestCase):
    """OperationalState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test OperationalState
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = meo_client.models.operational_state.OperationalState()  # noqa: E501
        if include_optional :
            return OperationalState(
            )
        else :
            return OperationalState(
        )

    def testOperationalState(self):
        """Test OperationalState"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
