# coding: utf-8

"""
    MEO Mm1 AppPkgMgmt API

    Implementation of Mm1.AppPkgm APIs  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import meo_client
from meo_client.api.default_api import DefaultApi  # noqa: E501
from meo_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = meo_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_app_packages_app_pkgm_v1_app_packages_get(self):
        """Test case for get_app_packages_app_pkgm_v1_app_packages_get

        Get App Packages  # noqa: E501
        """
        pass

    def test_onboard_app_package_app_pkgm_v1_app_packages_post(self):
        """Test case for onboard_app_package_app_pkgm_v1_app_packages_post

        Onboard App Package  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
